### ISSUE TITLE
note about WSL2

### ISSUE THREAD

**Issue by hhrhhr** [nmatsuda/viz1090#1]
For WSL2 instruction need be changed:

* run Xlaunch from the start menu
* Uncheck "Use Native openGL"
* **add additional parameter `-ac`** (enable public access)
* Open the Ubuntu WSL terminal
* Specify the X display to use
```
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0
```
* Start viz1090 as described below.

**Comment by nmatsuda** [comment]
Thanks for the heads up! I just updated the readme.
