### ISSUE TITLE
A similar project for massive visualizations (a link, comparison)

### ISSUE THREAD

**Issue by alexey-milovidov** [nmatsuda/viz1090#11]
I've created a similar application for the exploration of ADS-B datasets: https://github.com/ClickHouse/adsb.exposed
It could be useful for comparison.

A real-time demo is here: https://adsb.exposed/

It uses SQL instead of C++.
Maybe we can put a link for a reference to the list of similar projects.

**Comment by nmatsuda** [comment]
Ah cool, I will let you know if I add a related work section. The readme needs some updates now anyway.
