### ISSUE TITLE
The getmap script is unable to download the mapdata 

### ISSUE THREAD

**Issue by kalehmann** [nmatsuda/viz1090#12]
When I clone the repository, setup all the python stuff and the execute the `getmap.sh` script, it fails to download the map files:

```
$ ./getmap.sh 
--2024-04-10 16:20:29--  https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces.zip
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving www.naturalearthdata.com (www.naturalearthdata.com)... 50.87.253.14
Connecting to www.naturalearthdata.com (www.naturalearthdata.com)|50.87.253.14|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2024-04-10 16:20:30 ERROR 500: Internal Server Error.

--2024-04-10 16:20:30--  https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_populated_places.zip
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving www.naturalearthdata.com (www.naturalearthdata.com)... 50.87.253.14
Connecting to www.naturalearthdata.com (www.naturalearthdata.com)|50.87.253.14|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2024-04-10 16:20:31 ERROR 500: Internal Server Error.

--2024-04-10 16:20:31--  https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_airports.zip
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving www.naturalearthdata.com (www.naturalearthdata.com)... 50.87.253.14
Connecting to www.naturalearthdata.com (www.naturalearthdata.com)|50.87.253.14|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2024-04-10 16:20:32 ERROR 500: Internal Server Error.
```

At first this seems strange, as I can go to the [natural earth data downloads site](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/), select _Download states and provinces_ and download the file just fine from exactly the same link.

However if I just copy the link and paste it into the browser I also get the server error 500. I suspect they check the referrer there. 

To solve this issue I suggest to use direct links to the natural earth data CDN. These links are

- `https://naciscdn.org/naturalearth/10m/cultural/ne_10m_admin_1_states_provinces.zip`
- `https://naciscdn.org/naturalearth/10m/cultural/ne_10m_populated_places.zip`
- `https://naciscdn.org/naturalearth/10m/cultural/ne_10m_airports.zip`

They can either be obtained by going to the natural earth data site, downloading the files and checking the actual download link in the browser or by checking out older crawl data of these links in the Internet Archive:

- `https://web.archive.org/web/20231119212239/https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces.zip`
- `https://web.archive.org/web/20230307091850/https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_populated_places.zip`

I'll provide a pull request that changes these links in the script

**Comment by nmatsuda** [comment]
Thank you for this suggestion - I never figured out a clean way to handle  getting the maps, and it only works for those specific locations. I've merged your changes as this will at least fix the current issue.

**Comment by kalehmann** [comment]
Thanks. If you want a more clean way, there is also a GitHub repository with the map data at https://github.com/nvkelso/natural-earth-vector which seems linked to the naturalearthdata.com website.

Maybe pulling the files directly from there would be less error prone in the future.
