### ISSUE TITLE
Won't Build on Raspbian

### ISSUE THREAD

**Issue by LAX18** [nmatsuda/viz1090#2]
When I run through your instructions on Raspbian, I run into a dependency error with the required packages for building it. My raspberry pi is fully updated and upgraded. I can send logs tomorrow.

Also after what amount of time are aircraft taken off the map when signal is lost?

Thanks!

**Comment by nmatsuda** [comment]
hmm, I guess I'll have to see the logs. I just did a dist-upgrade and it still builds fine, but that doesn't mean one of the dependencies broke somewhere.

The aircraft is removed after 300 seconds, which is set with MODES_INTERACTIVE_DELETE_TTL in dump1090.h (this is just carried over from dump1090 as-is).

**Comment by LAX18** [comment]
It's very odd too as I tried building it on another pi just to see if it works and it worked. The only difference between the two is that one was flashed a few months later than the other. I can't wipe the other one as it has wayy more than dump1090 on it and I can't transfer all that data to a new distro.

Great work on this though, I installed it on my Linux pc and it works flawlessly!

**Comment by LAX18** [comment]
It's worth noting that I used RPI 4s for both builds

**Comment by LAX18** [comment]
Just got back to my PC, here are the logs
`pi@aa:~ $ sudo apt-get install libsdl2-dev libsdl2-ttf-dev libsdl2-gfx-dev librtlsdr-dev libgdal-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 librtlsdr-dev : Depends: librtlsdr0 (= 0.6-1) but 0.6-1+rpt1 is to be installed
 libsdl2-dev : Depends: libasound2-dev but it is not going to be installed
               Depends: libegl1-mesa-dev but it is not going to be installed
               Depends: libgl1-mesa-dev but it is not going to be installed
               Depends: libgles2-mesa-dev but it is not going to be installed
               Depends: libglu1-mesa-dev but it is not going to be installed
               Depends: libsdl2-2.0-0 (= 2.0.9+dfsg1-1) but 2.0.9+dfsg1-1+rpt1 is to be installed
E: Unable to correct problems, you have held broken packages.`

**Comment by nmatsuda** [comment]
I think this is an issue with your package versions being out of sync. The easiest thing to do might be to purge all the listed packages, check to make sure that there are no remaining versions, and then install all of them again.

**Comment by LAX18** [comment]
Ah I just figured it out. My package source was for a mirror in the UK with apparently outdated packages. Changed it to the source of my other Pi and it works now. Thanks again!
