### ISSUE TITLE
Place Names Won't Show

### ISSUE THREAD

**Issue by voreisthescore** [nmatsuda/viz1090#3]
After adding `--mapnames` and `--minpop` I still cant get local cities to show on the map, the map converter successfully extracts the archive, and I'm using populated places from the Natural Earth site. It seems however to default to the default place names, as it still grabs that archive. Any steps to troubleshoot this? Perhaps being able to specify at run time what map data I want to use rather than when grabbing the maps? [Here](https://www.naturalearthdata.com/downloads/110m-cultural-vectors/110m-populated-places/) is a link to the data used.

**Comment by nmatsuda** [comment]
What value are you passing to minpop? Are you seeing any place names at all?

**Comment by voreisthescore** [comment]
minpop is set to 50000, my city has over 100000 so it should show regardless, but doesn't unfortunately. I am seeing cities but just the Major cities. I'm in Australia so only seeing Sydney, Brisbane etc. Also of note that when I run get maps it extracts my `ne_110m_populated_places` first, and then also extracts the default `ne_10m_populated_places` not sure if maybe its overwriting my choice. 

Full command I ran was `./getmap.sh --mapnames  ne_110m_populated_places.zip --minpop 50000`
This was run in a completely clean directory and build of viz1090. Thanks for the quick reply!

**Comment by nmatsuda** [comment]
Ah, so the getmap bash script doesn't pass any arguments to mapconverter.py so it's still just running the defaults. To use different values you will need to either run mapconvert.py directly, or edit getmap.sh to use the source files and parameters you want.

**Comment by voreisthescore** [comment]
Im an idiot, thanks for your help, that fixed it. Is there anyway for me to pass in data without a Population value, I have a shape file for place names from my local state government but it doesn't have population values in it so fails looking for the key POP_MIN. This one has more place names that the natural earth data does.

**Comment by nmatsuda** [comment]
This converter was just the minimum effort way for me to get a map in my area so unfortunately it's not going to work as-is for other data sources. That said, if the rest of the format is the same I think you can delete lines 87 and 90 in mapconverter.py and unindent 91-93. It should then put all the place names in your file onto the map.

**Comment by voreisthescore** [comment]
Thanks for your help, managed to get it to work! Although I should probably get a data set with some populations numbers: Pic related.
![Screen Shot 2021-06-10 at 10 36 01 pm](https://user-images.githubusercontent.com/79523118/121525998-518d5f00-ca3c-11eb-8b99-c4b7c81af861.png)
Thanks again!
