### ISSUE TITLE
Cannot convert map data

### ISSUE THREAD

**Issue by phanus** [nmatsuda/viz1090#4]
First of all, thank you for all of your work, I'm running the viz1090 on Raspberry Pi and it looks very nice. I struggle to download and convert the map data. Running the mapconvert script ends with following error:

Archive:  ne_10m_admin_1_states_provinces.zip
inflating: ne_10m_admin_1_states_provinces.README.html
extracting: ne_10m_admin_1_states_provinces.VERSION.txt
extracting: ne_10m_admin_1_states_provinces.cpg
inflating: ne_10m_admin_1_states_provinces.dbf
inflating: ne_10m_admin_1_states_provinces.prj
inflating: ne_10m_admin_1_states_provinces.shp
inflating: ne_10m_admin_1_states_provinces.shx

4 archives were successfully processed.
Extracting map lines
  0%|                                                                              | 2/4596 [00:00<04:23, 17.43it/s]
Traceback (most recent call last):
  File "/home/user/viz1090/mapconverter.py", line 67, in <module>
    outlist = extractLines(shapefile, args.tolerance)
  File "/home/user/viz1090/mapconverter.py", line 41, in extractLines
    for boundary in simplified.boundary:
TypeError: 'MultiLineString' object is not iterable_

Can you please advise how to fix the script? Thank you!

**Comment by nmatsuda** [comment]
hmm it looks like something changed in the Shapely package. This might be
the fix:
https://gis.stackexchange.com/questions/456266/error-of-multilinestring-object-is-not-iterable

I will look at it later and update.

**Comment by nmatsuda** [comment]
ok sorry for the delay, I updated this in mapconverted.py in the main branch and it's working on my end.

**Comment by phanus** [comment]
Works like a charm, thank you for the quick fix.
