### ISSUE TITLE
Some planes don't show tag data

### ISSUE THREAD

**Issue by dlasher** [nmatsuda/viz1090#6]
Love this project, thank you, been looking for some way to have a live plane display without the overhead of X11/etc - fantastic for lower powered machines (PI/etc)

### Hardware
```
https://www.hardkernel.com/shop/odroid-n2-with-2gbyte-ram-2/
```

### Software
```
dietpi 9.0.2 bookworm
Linux odroid-n2+ 6.1.63-current-meson64 #1 SMP PREEMPT Mon Nov 20 10:52:19 UTC 2023 aarch64 GNU/Linux
```

### Issue
Some of the planes don't show tag data, some do. Opening the same view in tar1090/dump1090, all the planes have data. Same datasource (ADS-B) - same everything?

not sure where/how to help troubleshoot, but would love to see it working correctly.
 
Thanks!

### Image 
![signal-2024-02-01-105715](https://github.com/nmatsuda/viz1090/assets/937979/b6d5ee8c-084c-4af4-980c-50a116327efe)

**Comment by LAX18** [comment]
I apologize for cluttering this issue up, I was working on the exact same problem yesterday, a live plane display without the overhead of X11. Curious what you came up with for solutions. If you have Discord, please add me (lax18) or shoot me an email gaminglax18@gmail.com. Thanks!

**Comment by nmatsuda** [comment]
Yeah this is expected, but not fully implemented, behavior. It’s an attempt at automatically reducing visual clutter based on the density of the labels. There are three draw levels,

- 0: altitude, speed, and flight number
- 1: only the flight number
- 2:  only the plane icon

The draw level is selected in AircraftLabel.cpp in this section starting around line 256:

``` 

float density_mult = 0.5f;
float level_rate = 0.25f;
 	
if(elapsed(lastLevelChange) > 1000.0) {
    if(labelLevel < 0.8f * density_mult * calculateDensity(head, labelLevel + 1)) {
        if(labelLevel <= 2) {
            labelLevel += level_rate;
            lastLevelChange = now();
        }
} else if (labelLevel > 1.2f * density_mult * calculateDensity(head, labelLevel - 1)) {
        if(labelLevel >= 0) {
            labelLevel -= level_rate;
            lastLevelChange = now();
        }	                         
    }
 }
```
The density of the aircraft on screen is calculated before this, and then this block does some heuristic stuff like temporal smoothing and hysteresis to keep the label draw level from changing too often. `density_mult` coarsely changes when this happens. My plan is to make this adjustable with a quickly accessible on-screen slider but just haven’t gotten around to it (there are a bunch of things like this that will require a menu system). For now you can either fiddle with that variable or just comment out this section so `labelLevel` always remains at 0 (draw everything).

Let me know if that does what you’re looking for.

**Comment by dlasher** [comment]
> Yeah this is expected, but not fully implemented, behavior. 
> Let me know if that does what you’re looking for.

Commented out that section, and now everything has labels!!! (including the things off the edge of the screen)

Would there be an "easy" way to have onscreen have labels, and offscreen not? For now I think that would be the perfect compromise.

@LAX18 : to answer your question - this works very well, while I haven't figured the maps thing out yet (and I do miss the plane list on the side like dump1090, and the weather map) it's a really good way to display active traffic with far less overhead. @nmatsuda is doing great work.

**Comment by LAX18** [comment]
Ah I misread. I was looking to run THIS without a x11 server. I'll return to my search lol. Thanks!

**Comment by dlasher** [comment]
>Let me know if that does what you’re looking for.

Two other things that would be nifty:
* keyboard shortcuts for zoom in/out
* some sort of "icon" indicating the LAT/LONG you put in the file. IE where is "home"

**Comment by dlasher** [comment]
> Ah I misread. I was looking to run THIS without a x11 server in a web browser on a pi. I'll return to my search lol. Thanks!

Yeah, doesn't do that. It uses SDL/SDL2 to display ON the pi, so far less overhead, but AFAIK, there are no "full featured" web browsers using SDL/SDL2. Surprised, but I suspect the performance wouldn't be much different than Chrome in Kiosk mode under X11.

**Comment by dlasher** [comment]
> Ah I misread. I was looking to run THIS without a x11 server in a web browser on a pi. I'll return to my search lol. Thanks!

Honestly, this version isn't *that* far behind dump1090/tar1090 in a web browser.. Couple more features, like plane list (with filters/columns) and a map list (with choices) and you have the same thing.

And the responsiveness / framerates on the SDL version are much better than dump1090 in a browser

Not to mention the ability to run this on a local LCD/attached display. (Something like this : https://www.amazon.com/SmartiPi-Touch-Official-Raspberry-Touchscreen/dp/B07WXK38YM)

**Comment by LAX18** [comment]
I have had this running on a Pi with an attached screen but my current project uses a Pi Zero in a portable setting with a iPad connected over bluetooth/wifi. While tar1090 works just fine, I like the asthetics of this project and was researching a way to forward the x11 over HTTP, but the pi zero is incapable of sustaining decent framerates.

**Comment by dlasher** [comment]
> I have had this running on a Pi with an attached screen but my current project uses a Pi Zero in a portable setting with a iPad connected over bluetooth/wifi. While tar1090 works just fine, I like the asthetics of this project and was researching a way to forward the x11 over HTTP, but the pi zero is incapable of sustaining decent framerates with tools like xpra.

Ahh - I see where you're going.. you're going to have two problems - (1) local render speed and (2) network forwarding speed. I wonder if something like a oDroid N2+ would have enough horsepower to handle both.

something else to consider. Beefy(er) machine doing the lifting, then something like this on the PiZero: https://github.com/DanielGibson/sdl2_vnc

**Comment by dlasher** [comment]
@LAX18 : The issue I reported is solved with the work around. Looking forward to your next sets of features. 👍

**Comment by nmatsuda** [comment]
> > Let me know if that does what you’re looking for.
> 
> Two other things that would be nifty:
> 
> * keyboard shortcuts for zoom in/out
> * some sort of "icon" indicating the LAT/LONG you put in the file. IE where is "home"

yep I've been running this on on a handheld game emulator and have been wanting to use the buttons for moving around. Keyboard settings should be another menu system thing. I was also thinking if adding a button fits the view to all planes that are currently active. 

I like the idea of the home icon, I will add that.

**Comment by dlasher** [comment]
> > > Let me know if that does what you’re looking for.
> > 
> > 
> > Two other things that would be nifty:
> > 
> > * keyboard shortcuts for zoom in/out
> > * some sort of "icon" indicating the LAT/LONG you put in the file. IE where is "home"
> 
> yep I've been running this on on a handheld game emulator and have been wanting to use the buttons for moving around. Keyboard settings should be another menu system thing. I was also thinking if adding a button fits the view to all planes that are currently active.
> 
> I like the idea of the home icon, I will add that.

I figured I should be a proper consumer, and open [feature request] tickets for these kind of things.. then you can 👍  or 👎  them, track progress etc.. Sorry about the volume, figured I'd break them apart. :)

**Comment by nmatsuda** [comment]
this is great - it will give me some external motivation to actually do it!

**Comment by dlasher** [comment]
One other note - getting the maps working took the following.

```
apt-get install libopenblas-base
export LD_LIBRARY_PATH=/usr/lib/openblas-base/
```
